#include "PluginEditor.h"
#include <array>
#include <vector>

namespace
{
const auto accent = juce::Colour::fromRGB(150, 100, 255);
const auto panelColour = juce::Colour::fromRGB(20, 19, 30);
const auto panelEdge = juce::Colour::fromRGB(57, 49, 78);
const juce::StringArray modulationSources { "None", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "Env 1", "Env 2", "Env 3", "Velocity", "Key", "Mod Wheel", "Aftertouch", "Macro 1", "Macro 2", "Macro 3", "Macro 4", "Brown", "Stochastic" };
const juce::StringArray modulationDestinations { "None", "Pitch", "Cutoff", "Resonance", "Osc Mix", "Detune", "Spread", "Drive", "Pulse Width", "NASTY Amount", "NASTY Deform", "NASTY Feedback", "NASTY Coupling", "NASTY Energy", "NASTY Damping", "NASTY Moment", "Sample Level", "Sample Position", "Sample Scan", "Sample Jitter", "Sample Tune" };
void setComponentsVisible(std::initializer_list<juce::Component*> components, bool visible) { for (auto* c : components) c->setVisible(visible); }
}

ParamKnob::ParamKnob(juce::AudioProcessorValueTreeState& state, const juce::String& parameterID, const juce::String& displayName)
{
    label.setText(displayName.toUpperCase(), juce::dontSendNotification); label.setJustificationType(juce::Justification::centred); label.setFont(juce::FontOptions(10.0f, juce::Font::bold)); label.setColour(juce::Label::textColourId, juce::Colours::white.withAlpha(0.60f)); addAndMakeVisible(label);
    slider.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag); slider.setTextBoxStyle(juce::Slider::TextBoxBelow, false, 72, 18); slider.setColour(juce::Slider::rotarySliderFillColourId, accent); slider.setColour(juce::Slider::rotarySliderOutlineColourId, juce::Colours::white.withAlpha(0.10f)); slider.setColour(juce::Slider::thumbColourId, juce::Colours::white.withAlpha(0.90f)); slider.setColour(juce::Slider::textBoxTextColourId, juce::Colours::white.withAlpha(0.78f)); slider.setColour(juce::Slider::textBoxOutlineColourId, juce::Colours::transparentBlack); addAndMakeVisible(slider);
    attachment = std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(state, parameterID, slider);
}
void ParamKnob::resized() { auto a = getLocalBounds(); label.setBounds(a.removeFromTop(18)); slider.setBounds(a); }

ParamCombo::ParamCombo(juce::AudioProcessorValueTreeState& state, const juce::String& parameterID, const juce::String& displayName, const juce::StringArray& choices)
{
    label.setText(displayName.toUpperCase(), juce::dontSendNotification); label.setJustificationType(juce::Justification::centredLeft); label.setFont(juce::FontOptions(10.0f, juce::Font::bold)); label.setColour(juce::Label::textColourId, juce::Colours::white.withAlpha(0.58f)); addAndMakeVisible(label);
    for (int i = 0; i < choices.size(); ++i) combo.addItem(choices[i], i + 1); combo.setColour(juce::ComboBox::backgroundColourId, juce::Colour::fromRGB(12, 12, 19)); combo.setColour(juce::ComboBox::outlineColourId, panelEdge); combo.setColour(juce::ComboBox::textColourId, juce::Colours::white.withAlpha(0.82f)); combo.setColour(juce::ComboBox::arrowColourId, accent); addAndMakeVisible(combo);
    attachment = std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(state, parameterID, combo);
}
void ParamCombo::resized() { auto a = getLocalBounds(); label.setBounds(a.removeFromTop(17)); combo.setBounds(a.reduced(0, 2)); }

OmnariaAudioProcessorEditor::OmnariaAudioProcessorEditor(OmnariaAudioProcessor& p)
    : AudioProcessorEditor(&p), processor(p), discoverEngine(p.parameters), instructionEngine(p.parameters), globe(p.getEngineState()),
      oscAShape(p.parameters, "oscA_shape", "Osc A", { "Saw", "Pulse", "Sine" }), oscBShape(p.parameters, "oscB_shape", "Osc B", { "Saw", "Pulse", "Sine" }), phaseMode(p.parameters, "phase_mode", "Phase Mode", { "Retrig", "Random" }),
      oscMix(p.parameters, "osc_mix", "Mix"), oscBCoarse(p.parameters, "oscB_coarse", "B Tune"), pulseWidth(p.parameters, "pulse_width", "Pulse"), phase(p.parameters, "phase", "Phase"), unison(p.parameters, "unison", "Unison"), detune(p.parameters, "detune", "Detune"), spread(p.parameters, "spread", "Spread"), subLevel(p.parameters, "sub_level", "Sub"), subOctave(p.parameters, "sub_octave", "Sub Oct"), noiseLevel(p.parameters, "noise_level", "Noise"),
      filterMode(p.parameters, "filter_mode", "Filter", { "LP12", "LP24", "HP12", "BP12" }), filterCharacter(p.parameters, "filter_character", "Character", { "Clean", "Warm", "Acid", "Driven" }), filterCharacterAmount(p.parameters, "filter_character_amount", "Character"), cutoff(p.parameters, "cutoff", "Cutoff"), resonance(p.parameters, "resonance", "Resonance"), keytrack(p.parameters, "keytrack", "Keytrack"), drive(p.parameters, "drive", "Drive"), filterEnvAmount(p.parameters, "filter_env_amt", "Filt Env"), velocityTimbre(p.parameters, "velocity_timbre", "Velocity"), filterAttack(p.parameters, "filter_attack", "F Attack"), filterDecay(p.parameters, "filter_decay", "F Decay"), filterSustain(p.parameters, "filter_sustain", "F Sustain"), filterRelease(p.parameters, "filter_release", "F Release"), attack(p.parameters, "attack", "Attack"), decay(p.parameters, "decay", "Decay"), sustain(p.parameters, "sustain", "Sustain"), release(p.parameters, "release", "Release"),
      motion(p.parameters, "motion", "Motion"), history(p.parameters, "history", "History"), focus(p.parameters, "focus", "Focus"), coupling(p.parameters, "coupling", "Coupling"), output(p.parameters, "output", "Output"),
      nastyModel(p.parameters, "nasty_model", "NASTY Model", { "Fold", "Feedback", "Coupled", "Duffing" }), nastyAmount(p.parameters, "nasty_amount", "Amount"), nastyDeform(p.parameters, "nasty_deform", "Deform"), nastyFeedback(p.parameters, "nasty_feedback", "Feedback"), nastyCoupling(p.parameters, "nasty_coupling", "Coupling"), nastyEnergy(p.parameters, "nasty_energy", "Energy"), nastyDamping(p.parameters, "nasty_damping", "Damping"), nastyMoment(p.parameters, "nasty_moment", "Moment"),
      sampleMode(p.parameters, "sample_mode", "Mode", { "One Shot", "Loop", "Texture" }), sampleLevel(p.parameters, "sample_level", "Level"), sampleTune(p.parameters, "sample_tune", "Tune"), sampleStart(p.parameters, "sample_start", "Start"), sampleEnd(p.parameters, "sample_end", "End"), samplePosition(p.parameters, "sample_position", "Position"), sampleScan(p.parameters, "sample_scan", "Scan"), sampleJitter(p.parameters, "sample_jitter", "Jitter"),
      fxOrder(p.parameters, "fx_order", "Order", { "Motion>Delay>Space", "Delay>Motion>Space" }), fxDelayDivision(p.parameters, "fx_delay_div", "Delay", { "4/1", "2/1", "1/1", "1/2", "1/4", "3/4", "3/8", "1/8" }), fxMotionMix(p.parameters, "fx_motion_mix", "Motion"), fxMotionRate(p.parameters, "fx_motion_rate", "Rate"), fxMotionDepth(p.parameters, "fx_motion_depth", "Depth"), fxDelayMix(p.parameters, "fx_delay_mix", "Delay Mix"), fxDelayFeedback(p.parameters, "fx_delay_feedback", "Feedback"), fxSpaceMix(p.parameters, "fx_space_mix", "Space"), fxSpaceSize(p.parameters, "fx_space_size", "Size"), fxSpaceDamping(p.parameters, "fx_space_damping", "Damping"), fxWidth(p.parameters, "fx_width", "Width")
{
    setSize(1280, 980); setResizable(true, false); setResizeLimits(1180, 860, 1800, 1250);
    title.setText("OMNARIA", juce::dontSendNotification); title.setJustificationType(juce::Justification::centred); title.setFont(juce::FontOptions(30.0f, juce::Font::bold)); title.setColour(juce::Label::textColourId, juce::Colours::white.withAlpha(0.96f)); addAndMakeVisible(title);
    subtitle.setText("FLAGSHIP SYNTHESIZER", juce::dontSendNotification); subtitle.setJustificationType(juce::Justification::centred); subtitle.setFont(juce::FontOptions(10.0f, juce::Font::bold)); subtitle.setColour(juce::Label::textColourId, accent.withAlpha(0.92f)); addAndMakeVisible(subtitle);

    const std::vector<juce::Component*> mainComponents { &globe, &oscAShape, &oscBShape, &phaseMode, &oscMix, &oscBCoarse, &pulseWidth, &phase, &unison, &detune, &spread, &subLevel, &subOctave, &noiseLevel, &filterMode, &filterCharacter, &filterCharacterAmount, &cutoff, &resonance, &keytrack, &drive, &filterEnvAmount, &velocityTimbre, &filterAttack, &filterDecay, &filterSustain, &filterRelease, &attack, &decay, &sustain, &release, &motion, &history, &focus, &coupling, &output, &nastyModel, &nastyAmount, &nastyDeform, &nastyFeedback, &nastyCoupling, &nastyEnergy, &nastyDamping, &nastyMoment, &sampleMode, &sampleLevel, &sampleTune, &sampleStart, &sampleEnd, &samplePosition, &sampleScan, &sampleJitter, &fxOrder, &fxDelayDivision, &fxMotionMix, &fxMotionRate, &fxMotionDepth, &fxDelayMix, &fxDelayFeedback, &fxSpaceMix, &fxSpaceSize, &fxSpaceDamping, &fxWidth };
    for (auto* c : mainComponents) addAndMakeVisible(*c);

    sampleReverseAttachment = std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.parameters, "sample_reverse", sampleReverse); sampleReverse.setColour(juce::ToggleButton::textColourId, juce::Colours::white.withAlpha(0.75f)); addAndMakeVisible(sampleReverse);
    sampleNameLabel.setJustificationType(juce::Justification::centredLeft); sampleNameLabel.setColour(juce::Label::textColourId, juce::Colours::white.withAlpha(0.58f)); sampleNameLabel.setFont(juce::FontOptions(10.0f, juce::Font::bold)); addAndMakeVisible(sampleNameLabel);
    for (auto* button : { &loadSampleButton, &captureSampleButton, &nastyTabButton, &sampleTabButton, &fxTabButton }) { button->setColour(juce::TextButton::buttonColourId, accent.withAlpha(0.16f)); button->setColour(juce::TextButton::textColourOffId, juce::Colours::white.withAlpha(0.86f)); addAndMakeVisible(*button); }
    nastyTabButton.onClick = [this] { showSpecialistPage(0); }; sampleTabButton.onClick = [this] { showSpecialistPage(1); }; fxTabButton.onClick = [this] { showSpecialistPage(2); };
    loadSampleButton.onClick = [this] { sampleChooser = std::make_unique<juce::FileChooser>("Load sample", juce::File(), "*.wav;*.aif;*.aiff;*.flac;*.mp3"); sampleChooser->launchAsync(juce::FileBrowserComponent::openMode | juce::FileBrowserComponent::canSelectFiles, [this](const juce::FileChooser& chooser) { if (processor.loadSampleFile(chooser.getResult())) refreshSampleName(); }); };
    captureSampleButton.onClick = [this] { if (processor.captureRecentOutput()) refreshSampleName(); }; refreshSampleName();

    for (int i = 0; i < 4; ++i)
    {
        const auto s = juce::String(i + 1); lfoRates[i] = std::make_unique<ParamKnob>(p.parameters, "lfo" + s + "_rate", "LFO " + s + " Hz"); lfoModes[i] = std::make_unique<ParamCombo>(p.parameters, "lfo" + s + "_mode", "LFO " + s, juce::StringArray { "Free", "Retrig", "One Shot" }); macros[i] = std::make_unique<ParamKnob>(p.parameters, "macro" + s, "Macro " + s); modSources[i] = std::make_unique<ParamCombo>(p.parameters, "mod" + s + "_source", "Source " + s, modulationSources); modDestinations[i] = std::make_unique<ParamCombo>(p.parameters, "mod" + s + "_dest", "Destination " + s, modulationDestinations); modDepths[i] = std::make_unique<ParamKnob>(p.parameters, "mod" + s + "_depth", "Depth " + s);
        addAndMakeVisible(*lfoRates[i]); addAndMakeVisible(*lfoModes[i]); addAndMakeVisible(*macros[i]); addAndMakeVisible(*modSources[i]); addAndMakeVisible(*modDestinations[i]); addAndMakeVisible(*modDepths[i]); bindInstruction(*lfoRates[i], "lfo" + s + "_rate"); bindInstruction(*macros[i], "macro" + s); bindInstruction(*modDepths[i], "mod" + s + "_depth");
    }

    discoverButton.setColour(juce::TextButton::buttonColourId, accent.withAlpha(0.28f)); discoverButton.setColour(juce::TextButton::textColourOffId, juce::Colours::white.withAlpha(0.94f)); addAndMakeVisible(discoverButton); undoDiscoverButton.setColour(juce::TextButton::buttonColourId, juce::Colours::white.withAlpha(0.07f)); undoDiscoverButton.setColour(juce::TextButton::textColourOffId, juce::Colours::white.withAlpha(0.72f)); addAndMakeVisible(undoDiscoverButton);
    discoverWtf.setSliderStyle(juce::Slider::LinearHorizontal); discoverWtf.setTextBoxStyle(juce::Slider::NoTextBox, false, 0, 0); discoverWtf.setRange(0.0, 1.0, 0.01); discoverWtf.setColour(juce::Slider::trackColourId, accent.withAlpha(0.55f)); discoverWtf.setColour(juce::Slider::thumbColourId, juce::Colours::white.withAlpha(0.90f)); addAndMakeVisible(discoverWtf); discoverWtf.setValue(static_cast<double>(p.parameters.state.getProperty("discover_wtf", 0.35)), juce::dontSendNotification);
    familiarLabel.setText("FAM", juce::dontSendNotification); wtfLabel.setText("WTF", juce::dontSendNotification); lockLabel.setText("LOCK", juce::dontSendNotification); for (auto* label : { &familiarLabel, &wtfLabel, &lockLabel }) { label->setFont(juce::FontOptions(8.0f, juce::Font::bold)); label->setColour(juce::Label::textColourId, juce::Colours::white.withAlpha(0.50f)); label->setJustificationType(juce::Justification::centred); addAndMakeVisible(*label); }
    auto setupLock = [&p, this](juce::TextButton& button, const char* property) { button.setClickingTogglesState(true); button.setToggleState(static_cast<bool>(p.parameters.state.getProperty(property, false)), juce::dontSendNotification); button.setColour(juce::TextButton::buttonColourId, juce::Colours::white.withAlpha(0.05f)); button.setColour(juce::TextButton::buttonOnColourId, accent.withAlpha(0.42f)); button.setColour(juce::TextButton::textColourOffId, juce::Colours::white.withAlpha(0.62f)); button.setColour(juce::TextButton::textColourOnId, juce::Colours::white.withAlpha(0.96f)); button.onClick = [this] { persistDiscoverSettings(); }; addAndMakeVisible(button); };
    setupLock(lockCoreButton, "discover_lock_core"); setupLock(lockNastyButton, "discover_lock_nasty"); setupLock(lockSampleButton, "discover_lock_sample"); setupLock(lockModButton, "discover_lock_mod");
    discoverWtf.onValueChange = [this] { persistDiscoverSettings(); };
    discoverButton.onClick = [this]
    {
        const auto wtf = static_cast<float>(discoverWtf.getValue());
        const auto locks = getDiscoverLocks();
        discoverEngine.discover(wtf, locks, processor.getSampleName() != "EMPTY");
        Phase7Discover::evolve(processor.parameters, wtf, (locks & DiscoverEngine::lockCore) != 0u);
        refreshDiscoverUndo();
    };
    undoDiscoverButton.onClick = [this] { discoverEngine.undo(); refreshDiscoverUndo(); }; refreshDiscoverUndo();

    instructionModeButton.setColour(juce::TextButton::buttonColourId, juce::Colours::white.withAlpha(0.06f)); instructionModeButton.setColour(juce::TextButton::textColourOffId, juce::Colours::white.withAlpha(0.72f)); instructionModeButton.onClick = [this] { cycleInstructionMode(); }; addAndMakeVisible(instructionModeButton);
    instructionTitle.setFont(juce::FontOptions(11.0f, juce::Font::bold)); instructionTitle.setColour(juce::Label::textColourId, accent.withAlpha(0.95f)); addAndMakeVisible(instructionTitle); instructionText.setFont(juce::FontOptions(11.0f)); instructionText.setColour(juce::Label::textColourId, juce::Colours::white.withAlpha(0.80f)); instructionText.setJustificationType(juce::Justification::centredLeft); addAndMakeVisible(instructionText);
    for (auto* b : { &instructionTryButton, &instructionUndoButton }) { b->setColour(juce::TextButton::buttonColourId, accent.withAlpha(0.20f)); b->setColour(juce::TextButton::textColourOffId, juce::Colours::white.withAlpha(0.88f)); addAndMakeVisible(*b); }
    instructionTryButton.onClick = [this] { if (instructionEngine.applyTry(currentInstruction)) { instructionUndoButton.setEnabled(true); if (instructionEngine.getMode() == InstructionEngine::Mode::teach) showInstruction(instructionEngine.teach()); } }; instructionUndoButton.onClick = [this] { instructionEngine.undoTry(); instructionUndoButton.setEnabled(false); if (instructionEngine.getMode() == InstructionEngine::Mode::teach) showInstruction(instructionEngine.teach()); };
    for (auto pair : std::initializer_list<std::pair<ParamKnob*, juce::String>> { { &unison, "unison" }, { &detune, "detune" }, { &spread, "spread" }, { &cutoff, "cutoff" }, { &resonance, "resonance" }, { &drive, "drive" }, { &filterEnvAmount, "filter_env_amt" }, { &filterCharacterAmount, "filter_character_amount" }, { &nastyAmount, "nasty_amount" }, { &nastyFeedback, "nasty_feedback" }, { &nastyMoment, "nasty_moment" }, { &sampleLevel, "sample_level" }, { &sampleScan, "sample_scan" }, { &sampleJitter, "sample_jitter" }, { &fxMotionMix, "fx_motion_mix" }, { &fxDelayMix, "fx_delay_mix" }, { &fxSpaceMix, "fx_space_mix" } }) bindInstruction(*pair.first, pair.second);
    setInstructionMode(static_cast<InstructionEngine::Mode>(juce::jlimit(0, 2, static_cast<int>(p.parameters.state.getProperty("instruction_mode", 0)))), false); showSpecialistPage(0);
}

void OmnariaAudioProcessorEditor::bindInstruction(ParamKnob& knob, const juce::String& parameterID) { knob.slider.onValueChange = [this, parameterID] { const auto mode = instructionEngine.getMode(); if (mode == InstructionEngine::Mode::off) return; if (mode == InstructionEngine::Mode::help) showInstruction(instructionEngine.helpFor(parameterID)); else showInstruction(instructionEngine.teach()); }; }
void OmnariaAudioProcessorEditor::cycleInstructionMode() { const auto mode = instructionEngine.getMode(); setInstructionMode(mode == InstructionEngine::Mode::off ? InstructionEngine::Mode::help : mode == InstructionEngine::Mode::help ? InstructionEngine::Mode::teach : InstructionEngine::Mode::off, true); }
void OmnariaAudioProcessorEditor::setInstructionMode(InstructionEngine::Mode mode, bool persist) { instructionEngine.setMode(mode); const bool enabled = mode != InstructionEngine::Mode::off; instructionTitle.setVisible(enabled); instructionText.setVisible(enabled); instructionTryButton.setVisible(enabled); instructionUndoButton.setVisible(enabled); instructionModeButton.setButtonText(mode == InstructionEngine::Mode::off ? "?" : mode == InstructionEngine::Mode::help ? "HELP" : "TEACH"); if (persist) processor.parameters.state.setProperty("instruction_mode", static_cast<int>(mode), nullptr); if (mode == InstructionEngine::Mode::teach) { startTimerHz(2); showInstruction(instructionEngine.teach()); } else { stopTimer(); if (mode == InstructionEngine::Mode::help) showInstruction({ "HELP MODE", "Move a supported control and OMNARIA will explain what it does. Click HELP again for contextual TEACH mode." }); } resized(); repaint(); }
void OmnariaAudioProcessorEditor::showInstruction(const InstructionEngine::Suggestion& suggestion) { currentInstruction = suggestion; instructionTitle.setText(suggestion.title, juce::dontSendNotification); instructionText.setText(suggestion.body, juce::dontSendNotification); instructionTryButton.setButtonText(suggestion.hasAction ? suggestion.actionLabel : "TRY IT"); instructionTryButton.setEnabled(suggestion.hasAction); instructionUndoButton.setEnabled(instructionEngine.canUndoTry()); }
void OmnariaAudioProcessorEditor::timerCallback() { if (instructionEngine.getMode() == InstructionEngine::Mode::teach) showInstruction(instructionEngine.teach()); }
unsigned int OmnariaAudioProcessorEditor::getDiscoverLocks() const noexcept { unsigned int locks = 0; if (lockCoreButton.getToggleState()) locks |= DiscoverEngine::lockCore; if (lockNastyButton.getToggleState()) locks |= DiscoverEngine::lockNasty; if (lockSampleButton.getToggleState()) locks |= DiscoverEngine::lockSample; if (lockModButton.getToggleState()) locks |= DiscoverEngine::lockMod; return locks; }
void OmnariaAudioProcessorEditor::persistDiscoverSettings() { processor.parameters.state.setProperty("discover_wtf", discoverWtf.getValue(), nullptr); processor.parameters.state.setProperty("discover_lock_core", lockCoreButton.getToggleState(), nullptr); processor.parameters.state.setProperty("discover_lock_nasty", lockNastyButton.getToggleState(), nullptr); processor.parameters.state.setProperty("discover_lock_sample", lockSampleButton.getToggleState(), nullptr); processor.parameters.state.setProperty("discover_lock_mod", lockModButton.getToggleState(), nullptr); }
void OmnariaAudioProcessorEditor::refreshDiscoverUndo() { undoDiscoverButton.setEnabled(discoverEngine.canUndo()); }
void OmnariaAudioProcessorEditor::refreshSampleName() { sampleNameLabel.setText("SOURCE: " + processor.getSampleName(), juce::dontSendNotification); }

void OmnariaAudioProcessorEditor::showSpecialistPage(int page)
{
    specialistPage = juce::jlimit(0, 2, page); const bool n = specialistPage == 0, s = specialistPage == 1, f = specialistPage == 2;
    setComponentsVisible({ &nastyModel, &nastyAmount, &nastyDeform, &nastyFeedback, &nastyCoupling, &nastyEnergy, &nastyDamping, &nastyMoment }, n);
    setComponentsVisible({ &sampleMode, &sampleLevel, &sampleTune, &sampleStart, &sampleEnd, &samplePosition, &sampleScan, &sampleJitter, &sampleReverse, &loadSampleButton, &captureSampleButton, &sampleNameLabel }, s);
    setComponentsVisible({ &fxOrder, &fxDelayDivision, &fxMotionMix, &fxMotionRate, &fxMotionDepth, &fxDelayMix, &fxDelayFeedback, &fxSpaceMix, &fxSpaceSize, &fxSpaceDamping, &fxWidth }, f);
    nastyTabButton.setToggleState(n, juce::dontSendNotification); sampleTabButton.setToggleState(s, juce::dontSendNotification); fxTabButton.setToggleState(f, juce::dontSendNotification); resized(); repaint();
}

void OmnariaAudioProcessorEditor::paint(juce::Graphics& g)
{
    g.fillAll(juce::Colour::fromRGB(8, 8, 13)); auto body = getLocalBounds().toFloat(); body.removeFromTop(76.0f); auto modulationStrip = body.removeFromBottom(246.0f).reduced(14.0f, 8.0f); auto specialistStrip = body.removeFromBottom(124.0f).reduced(14.0f, 6.0f); auto stateStrip = body.removeFromBottom(118.0f).reduced(14.0f, 6.0f); body = body.reduced(14.0f, 8.0f); auto left = body.removeFromLeft(350.0f), right = body.removeFromRight(430.0f), centre = body.reduced(10.0f, 0.0f);
    for (const auto& panel : { left, centre, right, stateStrip, specialistStrip, modulationStrip }) { g.setColour(panelColour); g.fillRoundedRectangle(panel, 15.0f); g.setColour(panelEdge.withAlpha(0.80f)); g.drawRoundedRectangle(panel, 15.0f, 1.0f); }
    g.setColour(juce::Colours::white.withAlpha(0.48f)); g.setFont(juce::FontOptions(10.0f, juce::Font::bold)); g.drawText("CORE OSCILLATORS", left.withTrimmedLeft(14.0f).removeFromTop(24.0f), juce::Justification::centredLeft); g.drawText("ENGINE STATE", centre.withTrimmedLeft(14.0f).removeFromTop(24.0f), juce::Justification::centredLeft); g.drawText("FILTER / EXPRESSION / AMP", right.withTrimmedLeft(14.0f).removeFromTop(24.0f), juce::Justification::centredLeft); g.drawText("PERFORMANCE", stateStrip.withTrimmedLeft(14.0f).removeFromTop(24.0f), juce::Justification::centredLeft);
    const auto specialistTitle = specialistPage == 0 ? "NASTY — MOMENT ENGINE" : specialistPage == 1 ? "SAMPLE — SYNTHESIS / RESAMPLE" : "FX — PRODUCTION / SPACE"; g.drawText(specialistTitle, specialistStrip.withTrimmedLeft(260.0f).removeFromTop(24.0f), juce::Justification::centredLeft); g.drawText("MODULATION — VISIBLE ROUTING", modulationStrip.withTrimmedLeft(14.0f).removeFromTop(24.0f), juce::Justification::centredLeft);
    g.setColour(juce::Colours::white.withAlpha(0.72f)); g.setFont(juce::FontOptions(15.0f)); g.drawText("LATHAM", 20, 20, 90, 24, juce::Justification::centredLeft, false); g.setFont(juce::FontOptions(15.0f, juce::Font::bold)); g.drawText("AUDIO", 78, 20, 74, 24, juce::Justification::centredLeft, false);
    if (instructionEngine.getMode() != InstructionEngine::Mode::off) { auto card = juce::Rectangle<float>(static_cast<float>(getWidth() - 520), 70.0f, 490.0f, 86.0f); g.setColour(juce::Colour::fromRGB(14, 13, 22).withAlpha(0.98f)); g.fillRoundedRectangle(card, 12.0f); g.setColour(accent.withAlpha(0.55f)); g.drawRoundedRectangle(card, 12.0f, 1.0f); }
}

void OmnariaAudioProcessorEditor::resized()
{
    const auto bounds = getLocalBounds(); title.setBounds(bounds.getCentreX() - 150, 10, 300, 38); subtitle.setBounds(bounds.getCentreX() - 150, 45, 300, 18); instructionModeButton.setBounds(bounds.getRight() - 70, 20, 46, 30);
    if (instructionEngine.getMode() != InstructionEngine::Mode::off) { auto card = juce::Rectangle<int>(bounds.getRight() - 520, 70, 490, 86).reduced(10); instructionTitle.setBounds(card.removeFromTop(20)); auto actions = card.removeFromRight(120); instructionTryButton.setBounds(actions.removeFromTop(28).reduced(2)); instructionUndoButton.setBounds(actions.removeFromTop(28).reduced(2)); instructionText.setBounds(card.reduced(2)); }
    auto body = bounds; body.removeFromTop(76); auto modulationStrip = body.removeFromBottom(246).reduced(14, 8); auto specialistStrip = body.removeFromBottom(124).reduced(14, 6); auto stateStrip = body.removeFromBottom(118).reduced(14, 6); body = body.reduced(14, 8); auto left = body.removeFromLeft(350).reduced(12), right = body.removeFromRight(430).reduced(12), centre = body.reduced(10, 8);
    left.removeFromTop(24); auto comboRow = left.removeFromTop(50); const auto comboCell = comboRow.getWidth() / 3; oscAShape.setBounds(comboRow.removeFromLeft(comboCell)); oscBShape.setBounds(comboRow.removeFromLeft(comboCell)); phaseMode.setBounds(comboRow); const auto oscH = juce::jmax(70, left.getHeight() / 3); auto r1 = left.removeFromTop(oscH); auto c1 = r1.getWidth() / 4; oscMix.setBounds(r1.removeFromLeft(c1)); oscBCoarse.setBounds(r1.removeFromLeft(c1)); pulseWidth.setBounds(r1.removeFromLeft(c1)); phase.setBounds(r1); auto r2 = left.removeFromTop(oscH); auto c2 = r2.getWidth() / 3; unison.setBounds(r2.removeFromLeft(c2)); detune.setBounds(r2.removeFromLeft(c2)); spread.setBounds(r2); auto r3 = left; auto c3 = r3.getWidth() / 3; subLevel.setBounds(r3.removeFromLeft(c3)); subOctave.setBounds(r3.removeFromLeft(c3)); noiseLevel.setBounds(r3);
    centre.removeFromTop(18); globe.setBounds(centre); right.removeFromTop(24); auto filterHead = right.removeFromTop(50); filterMode.setBounds(filterHead.removeFromLeft(filterHead.getWidth() / 2).reduced(2)); filterCharacter.setBounds(filterHead.reduced(2)); const auto rightH = juce::jmax(70, right.getHeight() / 3); auto tone = right.removeFromTop(rightH); const auto toneC = tone.getWidth() / 7; cutoff.setBounds(tone.removeFromLeft(toneC)); resonance.setBounds(tone.removeFromLeft(toneC)); keytrack.setBounds(tone.removeFromLeft(toneC)); filterEnvAmount.setBounds(tone.removeFromLeft(toneC)); velocityTimbre.setBounds(tone.removeFromLeft(toneC)); drive.setBounds(tone.removeFromLeft(toneC)); filterCharacterAmount.setBounds(tone); auto fenv = right.removeFromTop(rightH); const auto envC = fenv.getWidth() / 4; filterAttack.setBounds(fenv.removeFromLeft(envC)); filterDecay.setBounds(fenv.removeFromLeft(envC)); filterSustain.setBounds(fenv.removeFromLeft(envC)); filterRelease.setBounds(fenv); auto aenv = right; const auto aC = aenv.getWidth() / 4; attack.setBounds(aenv.removeFromLeft(aC)); decay.setBounds(aenv.removeFromLeft(aC)); sustain.setBounds(aenv.removeFromLeft(aC)); release.setBounds(aenv);
    stateStrip.removeFromTop(24); const auto stateC = stateStrip.getWidth() / 5; motion.setBounds(stateStrip.removeFromLeft(stateC)); history.setBounds(stateStrip.removeFromLeft(stateC)); focus.setBounds(stateStrip.removeFromLeft(stateC)); coupling.setBounds(stateStrip.removeFromLeft(stateC)); output.setBounds(stateStrip);

    auto header = specialistStrip.removeFromTop(26); nastyTabButton.setBounds(header.removeFromLeft(76).reduced(2)); sampleTabButton.setBounds(header.removeFromLeft(76).reduced(2)); fxTabButton.setBounds(header.removeFromLeft(76).reduced(2));
    if (specialistPage == 0) { const auto cell = specialistStrip.getWidth() / 8; nastyModel.setBounds(specialistStrip.removeFromLeft(cell)); nastyAmount.setBounds(specialistStrip.removeFromLeft(cell)); nastyDeform.setBounds(specialistStrip.removeFromLeft(cell)); nastyFeedback.setBounds(specialistStrip.removeFromLeft(cell)); nastyCoupling.setBounds(specialistStrip.removeFromLeft(cell)); nastyEnergy.setBounds(specialistStrip.removeFromLeft(cell)); nastyDamping.setBounds(specialistStrip.removeFromLeft(cell)); nastyMoment.setBounds(specialistStrip); }
    else if (specialistPage == 1) { auto sampleControls = specialistStrip; auto actionArea = sampleControls.removeFromRight(210); sampleNameLabel.setBounds(actionArea.removeFromTop(24)); auto buttons = actionArea.removeFromTop(32); loadSampleButton.setBounds(buttons.removeFromLeft(86).reduced(2)); captureSampleButton.setBounds(buttons.removeFromLeft(112).reduced(2)); sampleReverse.setBounds(actionArea.removeFromTop(28)); const auto cell = sampleControls.getWidth() / 8; sampleMode.setBounds(sampleControls.removeFromLeft(cell)); sampleLevel.setBounds(sampleControls.removeFromLeft(cell)); sampleTune.setBounds(sampleControls.removeFromLeft(cell)); sampleStart.setBounds(sampleControls.removeFromLeft(cell)); sampleEnd.setBounds(sampleControls.removeFromLeft(cell)); samplePosition.setBounds(sampleControls.removeFromLeft(cell)); sampleScan.setBounds(sampleControls.removeFromLeft(cell)); sampleJitter.setBounds(sampleControls); }
    else { auto fx = specialistStrip; const auto comboW = juce::jmax(110, fx.getWidth() / 9); fxOrder.setBounds(fx.removeFromLeft(comboW).reduced(2)); fxDelayDivision.setBounds(fx.removeFromLeft(comboW).reduced(2)); const auto cell = juce::jmax(70, fx.getWidth() / 9); fxMotionMix.setBounds(fx.removeFromLeft(cell)); fxMotionRate.setBounds(fx.removeFromLeft(cell)); fxMotionDepth.setBounds(fx.removeFromLeft(cell)); fxDelayMix.setBounds(fx.removeFromLeft(cell)); fxDelayFeedback.setBounds(fx.removeFromLeft(cell)); fxSpaceMix.setBounds(fx.removeFromLeft(cell)); fxSpaceSize.setBounds(fx.removeFromLeft(cell)); fxSpaceDamping.setBounds(fx.removeFromLeft(cell)); fxWidth.setBounds(fx); }

    auto discoverHeader = modulationStrip.removeFromTop(24); auto d = discoverHeader.removeFromRight(622).reduced(2, 0); lockLabel.setBounds(d.removeFromLeft(34)); for (auto* b : { &lockCoreButton, &lockNastyButton, &lockSampleButton, &lockModButton }) b->setBounds(d.removeFromLeft(54).reduced(2, 1)); familiarLabel.setBounds(d.removeFromLeft(28)); discoverWtf.setBounds(d.removeFromLeft(128).reduced(2, 2)); wtfLabel.setBounds(d.removeFromLeft(28)); undoDiscoverButton.setBounds(d.removeFromLeft(62).reduced(2, 1)); discoverButton.setBounds(d.reduced(2, 1));
    auto sourceRow = modulationStrip.removeFromTop(82); const auto sourceC = sourceRow.getWidth() / 8; for (int i = 0; i < 4; ++i) lfoRates[i]->setBounds(sourceRow.removeFromLeft(sourceC)); for (int i = 0; i < 4; ++i) macros[i]->setBounds(sourceRow.removeFromLeft(sourceC)); auto modeRow = modulationStrip.removeFromTop(44); const auto modeC = modeRow.getWidth() / 4; for (int i = 0; i < 4; ++i) lfoModes[i]->setBounds(modeRow.removeFromLeft(modeC).reduced(4, 0)); auto routeRow = modulationStrip; const auto routeC = routeRow.getWidth() / 4; for (int i = 0; i < 4; ++i) { auto slot = routeRow.removeFromLeft(routeC).reduced(5, 0); auto depthArea = slot.removeFromRight(78); auto sourceArea = slot.removeFromTop(slot.getHeight() / 2); modSources[i]->setBounds(sourceArea); modDestinations[i]->setBounds(slot); modDepths[i]->setBounds(depthArea); }
}
